- id: '1609204696160'
  alias: HA config push to Git
  description: ''
  trigger:
  - platform: time
    at: '19:20'
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /config/ha_gitpush.sh
  mode: single
